package util

import (
	"slices"

	"github.com/klauspost/compress/zstd"
)

const (
	frameSize        = 1024
	initalHeaderSize = 13
	headerSize       = 8
	payloadSize      = frameSize - headerSize
	firstPayloadSize = frameSize - initalHeaderSize
	maxChunks        = 1920
)

func nsal(data []byte) ([][]byte, error) {
	enc, err := zstd.NewWriter(nil) // nil dest is fine for EncodeAll
	if err != nil {
		return err
	}
	defer enc.Close()

	compressed := enc.EncodeAll(data, nil)
	base128 := Encode(compressed)
}

// Chunk This verson of shoes' chunking functions (and such needed for it) are not generated by ai.
func Chunk(data []byte) ([][]byte, error) {
	head, tail := data[:firstPayloadSize], data[firstPayloadSize:]
	var chunks [][]byte
	if len(tail) > 0 {
		for chunk := range slices.Chunk(tail, payloadSize) {
			chunks = append(chunks, chunk)
		}
	}
	var total = len(chunks) + 1
	var temp = make([][]byte, total)
	temp[0] = head
	copy(temp[1:], chunks)
	chunks = temp

}

// README
/*
You may have noticed that I chose Zstd for compression. I promise that was done for a reason, along with how the chunking will work.
Currently, chunking works like this:
Data -> Compression (ZStd) -> Base128 Encode -> Is smaller?
                                             |-> Yes -> Send compressed version
                                             |-> No  -> Is the original data UTF-8 compliant?
                                                     |-> Yes -> Send original data
                                                     |-> No  -> Send base128ed version




*/
