package util

import (
	"encoding/binary"
	"errors"
	"hash/crc32"
	"unicode/utf8"

	"github.com/klauspost/compress/zstd"
)

const (
	frameSize        = 1024
	initalHeaderSize = 12 // message id (4) + base128'd crc32 (5) + count rune (2) + flags (1)
	headerSize       = 6  // message id (4) + count rune (2)
	payloadSize      = frameSize - headerSize
	firstPayloadSize = frameSize - initalHeaderSize
	maxChunks        = 1920
)

// Chunk This verson of shoes' chunking functions (and such needed for it) are not generated by ai.
func Chunk(data []byte) ([][]byte, error) {

	enc, err := zstd.NewWriter(nil) // nil dest is fine for EncodeAll
	if err != nil {
		return nil, err
	}
	defer enc.Close()

	compressed := enc.EncodeAll(data, nil)
	encodedCompressed := Encode(compressed)
	var isCompressed bool = false
	var isEncoded bool = false

	var active []byte
	if utf8.Valid(data) {
		if len(encodedCompressed) < len(data) {
			isCompressed = true
			isEncoded = true
			active = encodedCompressed
		} else {
			active = data
		}
	} else {
		encoded := Encode(data)
		if len(encodedCompressed) < len(encoded) {
			isCompressed = true
			isEncoded = true
			active = encodedCompressed
		} else {
			isEncoded = true
			active = encoded
		}
	}
	headLen := firstPayloadSize
	if headLen >= len(active) {
		headLen = len(active)
	} else {
		for headLen > 0 && !utf8.RuneStart(active[headLen]) {
			headLen--
		}
	}
	head, tail := active[:headLen], active[headLen:]
	chunks := make([][]byte, 0, 1+len(tail)/payloadSize+1)
	for len(tail) > 0 {
		if payloadSize >= len(tail) {
			chunks = append(chunks, tail)
			break
		}
		n := payloadSize
		for n > 0 && !utf8.RuneStart(tail[n]) {
			n--
		}
		if n == 0 {
			n = payloadSize
		}
		chunks = append(chunks, tail[:n])
		tail = tail[n:]
	}
	chunks = Prepend(chunks, head)

	crc32sum := make([]byte, 4)
	binary.BigEndian.PutUint32(crc32sum, crc32.ChecksumIEEE(active))
	var header = Header{
		Crc32: Encode(crc32sum),
		Flags: Flags{
			Compressed: isCompressed,
			Base128:    isEncoded,
		},
	}
	header.Flags.ProduceResult()
	err = header.ProduceMessageID()
	if err != nil {
		return nil, err
	}
	total := len(chunks)
	if total >= maxChunks {
		return nil, errors.New("total chunks exceeds limit (1919)")
	}
	chunks[0] = PrependArray(chunks[0], header.ProduceFirstHeader(total))

	for i := 1; i < total; i++ {
		chunks[i] = PrependArray(chunks[i], header.ProduceHeader(i+1))
	}
	return chunks, nil
}

// README
/*
You may have noticed that I chose Zstd for compression. I promise that was done for a reason, along with how the chunking will work.
Currently, chunking works like this:
Data -> Compression (ZStd) -> Base128 Encode -> Is smaller?
                                             |-> Yes -> Send compressed version
                                             |-> No  -> Is the original data UTF-8 compliant?
                                                     |-> Yes -> Send original data
                                                     |-> No  -> Send base128ed version




*/
